definitions:
  handler.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  main.ping:
    properties:
      message:
        example: pong
        type: string
    type: object
  model.AdminBody:
    properties:
      email:
        description: Phone         string   `json:"phone" validate:"required,number,min=10,max=12"`
        type: string
      fullname:
        maxLength: 30
        type: string
      groupId:
        type: integer
      permissionIds:
        items:
          type: integer
        type: array
      status:
        type: string
    required:
    - email
    - fullname
    - status
    type: object
  model.AdminCreateGroup:
    properties:
      groupId:
        type: integer
      permissionIds:
        items:
          type: integer
        type: array
    required:
    - groupId
    - permissionIds
    type: object
  model.AdminUpdateGroup:
    properties:
      groupId:
        type: integer
      permissionId:
        items:
          type: integer
        type: array
    required:
    - groupId
    - permissionId
    type: object
  model.AdminUpdatePassword:
    properties:
      password:
        maxLength: 30
        minLength: 8
        type: string
    required:
    - password
    type: object
  model.CreateAdmin:
    properties:
      adminGroupId:
        type: integer
      email:
        type: string
      fullname:
        maxLength: 30
        type: string
      password:
        maxLength: 30
        type: string
      permissionIds:
        items:
          type: integer
        type: array
      phone:
        maxLength: 12
        minLength: 10
        type: string
      roleId:
        type: string
      status:
        type: string
      username:
        maxLength: 30
        type: string
    required:
    - adminGroupId
    - email
    - fullname
    - password
    - permissionIds
    - phone
    - roleId
    - status
    - username
    type: object
  model.CreateGroup:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  model.CreatePermission:
    properties:
      permissions:
        items:
          $ref: '#/definitions/model.PermissionName'
        type: array
    required:
    - permissions
    type: object
  model.LoginAdmin:
    properties:
      ip:
        type: string
      password:
        maxLength: 30
        type: string
      username:
        maxLength: 30
        minLength: 8
        type: string
    required:
    - password
    - username
    type: object
  model.LoginResponse:
    properties:
      token:
        type: string
    type: object
  model.PermissionName:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  model.Success:
    properties:
      message:
        type: string
    type: object
  model.SuccessWithData:
    properties:
      data: {}
      message:
        type: string
    type: object
  model.SuccessWithList:
    properties:
      list: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /admins:
    get:
      consumes:
      - application/json
      description: Get Admin List
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Search
        in: query
        name: search
        type: string
      - description: Status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessWithList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get Admin List
      tags:
      - Admins
  /admins/create:
    post:
      consumes:
      - application/json
      description: Create Admin
      parameters:
      - description: Create Admin
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/model.CreateAdmin'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create Admin
      tags:
      - Admins
  /admins/detail/{id}:
    get:
      consumes:
      - application/json
      description: Get Admin
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessWithData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get Admin
      tags:
      - Admins
  /admins/group:
    get:
      consumes:
      - application/json
      description: Group List
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessWithList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Group List
      tags:
      - Admins
    post:
      consumes:
      - application/json
      description: Create Group
      parameters:
      - description: Create Group
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/model.AdminCreateGroup'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create Group
      tags:
      - Admins
  /admins/group/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Group
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete Group
      tags:
      - Admins
    get:
      consumes:
      - application/json
      description: Get Group
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessWithData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get Group
      tags:
      - Admins
    put:
      consumes:
      - application/json
      description: Update Group
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Group
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/model.AdminUpdateGroup'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update Group
      tags:
      - Admins
  /admins/password/{id}:
    put:
      consumes:
      - application/json
      description: Update Admin Password
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Admin Password
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/model.AdminUpdatePassword'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update Admin Password
      tags:
      - Admins
  /admins/permission/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Permission
      parameters:
      - description: Permission ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete Permission
      tags:
      - Admins
  /admins/update/{id}:
    put:
      consumes:
      - application/json
      description: Update Admin
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Admin
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/model.AdminBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update Admin
      tags:
      - Admins
  /groups/create:
    post:
      consumes:
      - application/json
      description: Create Group
      parameters:
      - description: Create Group
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/model.CreateGroup'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create Group
      tags:
      - Groups
  /login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/model.LoginAdmin'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Login
      tags:
      - Auth
  /permissions/create:
    post:
      consumes:
      - application/json
      description: Create Permission
      parameters:
      - description: Create Permission
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/model.CreatePermission'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create Permission
      tags:
      - Permissions
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ping'
      summary: ping example
      tags:
      - Test
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
