definitions:
  main.ping:
    properties:
      message:
        example: pong
        type: string
    type: object
  service.Pagination:
    properties:
      list: {}
      total:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/be/promotions:
    get:
      consumes:
      - application/json
      description: Get all promotions
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Sort
        in: query
        name: sort
        type: string
      - description: Order
        in: query
        name: order
        type: string
      - description: Search
        in: query
        name: search
        type: string
      - description: Filter
        in: query
        name: filter
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Pagination'
      summary: Get all promotions
      tags:
      - promotions backend
  /api/promotions:
    get:
      consumes:
      - application/json
      description: Get all promotions
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Sort
        in: query
        name: sort
        type: string
      - description: Order
        in: query
        name: order
        type: string
      - description: Search
        in: query
        name: search
        type: string
      - description: Filter
        in: query
        name: filter
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Pagination'
      summary: Get all promotions
      tags:
      - promotions
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ping'
      summary: ping example
      tags:
      - Test
swagger: "2.0"
